# Generated by Django 5.1.2 on 2024-10-21 00:20

import django.db.models.deletion
from django.db import migrations, models


def create_initial_roles(apps, schema_editor):
    Rol = apps.get_model('Crud_admin', 'Rol')  
    Rol.objects.create(nombre='Administrador')
    Rol.objects.create(nombre='Editor')
    Rol.objects.create(nombre='Usuario')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Add the dependencies if there are any previous migrations
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=60, unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('contacto', models.CharField(max_length=60)),
                ('correo', models.EmailField(max_length=60, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=100)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crud_admin.rol')),  # Replace 'your_app' with the name of your application
            ],
        ),
        migrations.RunPython(create_initial_roles),
    ]
