# Generated by Django 5.1.2 on 2024-10-21 21:40
import django.db.models.deletion
from django.db import migrations, models

def create_initial_roles(apps, schema_editor):
    Rol = apps.get_model('Crud_admin', 'Rol')  # Cambia 'Crud_admin' si tu app tiene otro nombre
    Rol.objects.create(nombre='Administrador')
    Rol.objects.create(nombre='Vendedor')
    Rol.objects.create(nombre='Comprador')

class Migration(migrations.Migration):

    dependencies = [
        ('Crud_admin', '0001_initial'),  # Asegúrate de que esta sea la migración anterior
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crud_admin.rol'),
        ),
        migrations.RunPython(create_initial_roles),  # Agrega esta línea para crear los roles
    ]
