# Generated by Django 5.1.2 on 2024-10-21 23:26

from django.db import migrations


def create_initial_roles_and_categories(apps, schema_editor):
    Rol = apps.get_model('Crud_admin', 'Rol')
    Categoria = apps.get_model('Crud_admin', 'Categoria')

    # Crear roles
    Rol.objects.get_or_create(nombre='Administrador')
    Rol.objects.get_or_create(nombre='Vendedor')
    Rol.objects.get_or_create(nombre='Usuario')

    # Crear categorías
    categorias = ['Hogar', 'Juguetes', 'Construcción', 'Accesorios']
    for nombre in categorias:
        Categoria.objects.get_or_create(nombre=nombre)

class Migration(migrations.Migration):

    dependencies = [
        ('Crud_admin', '0003_categoria_producto_venta'),
    ]

    operations = [
         migrations.RunPython(create_initial_roles_and_categories),
    ]
